### PR TITLE
Merge upstream release v2022.2.1

### PR DESCRIPTION
**Pull request by csett86**

### CODE REVIEW

**Comment by csett86** [comment]
@awlx To get this into release v2022.2.1 with the github actions CI:

- Draft a release 2022.2.1 with tag version v2022.2.1 now (the "v" prefix in the tag version is important, the release name can be anything)
- Merge this PR (which contains the version bump to 2022.2.1 in the package.json)
- See the github action running after the merge on the main branch, attaching the artifacts to the draft release 2022.2.1
- Download the artifacts and test them, if successful, publish the draft release 2022.2.1

**Comment by T0biii** [comment]
@csett86 don't we have to adjust that too ? https://github.com/freifunkMUC/jitsi-meet-electron/blob/693b49632a08bd7ae32e1d3e21d79d0ebfb22c06/package.json#L2
Because somehow otherwise jitsi-meet and Freifunk Meet will be installed in the same folder? (Tested with Windows, or will this break the update process ?)

**Comment by csett86** [comment]
@T0biii Good catch. This is like this since the fork exists, but yes, maybe its a good idea to adjust that going forward. Its only relevant for Windows, as on Mac the .app is named different and on Linux the AppImage is also already named differently.

I will test if it brakes the updater.

**Comment by csett86** [comment]
It does not break the updater, but it also does not "fix" existing installs, they stay at AppData\Local\Programs\jitsi-meet-electron. Nontheless going forward I think this is a good idea, thus I have pushed it as a followup commit.

**Pull request merged**
